services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: prod-nimblefast.com.br
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_URL_BASE=https://api.nimblefast.com.br
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AIzaSyCdW2cG_JlAQg3XcbbOtpvMESYoUHO9F_I
      - NEXT_PUBLIC_LEVEL_LOGGER=info #"fatal" | "error" | "warn" | "info" | "debug" | "trace";
      - NEXT_PUBLIC_GOOGLE_CLOUD_VISION_API_KEY=AIzaSyCdW2cG_JlAQg3XcbbOtpvMESYoUHO9F_I

    networks:
      - pg-network-prod

networks:
  pg-network-prod:
    external: true
